(function(){
  var labels={trend_breakout:"Trend kırılımı",pullback_reclaim:"Geri çekilme",liquidity_sweep:"Likidite süpürmesi",selective_trend_pullback:"Seçici trend",bollinger_reversion:"Bollinger dönüşü"};
  var explain={trend_breakout:"Güçlü hacimle kırılan trendi izler; hedef +%3 ROE, stop en az -%1,5 ROE'dir.",pullback_reclaim:"Trend içinde yeniden güçlenmeyi bekler; hedef +%3 ROE, stop en az -%1,5 ROE'dir.",liquidity_sweep:"Süpürmeden sonra ikinci 5dk mum teyidini bekler; hedef +%3 ROE, stop en az -%1,5 ROE'dir.",selective_trend_pullback:"BTC ve coin 1s yönü aynıyken 5dk geri çekilme arar; hedef +%3 ROE, stop en az -%1,5 ROE'dir.",bollinger_reversion:"Yalnızca 15dk alt/üst bandın dış %20 giriş bölgesinde işlem açar; hedef +%3 ROE, stop en az -%1,5 ROE ve risk/getiri en az 1,25'tir."};
  var colors={trend_breakout:"#52e1a0",pullback_reclaim:"#64cddd",liquidity_sweep:"#f1b95f",selective_trend_pullback:"#8b5cf6",bollinger_reversion:"#e8793f"};
  var copyWalletAddresses=["0xdc9bf10e6b88f0657d02179ca338e0ffe9ecc564","0x4721d4bcf69f585801362feac273e8389d1a45ec"];
  var days=7,data=null,selected="trend_breakout",tradingViewSymbol="",chartSelection="",tradeRange="today";
  function e(id){return document.getElementById(id)}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})}
  function n(v,d){if(v==null||v==="")return"—";v=Number(v);return Number.isFinite(v)?v.toLocaleString("tr-TR",{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d}):"—"}
  function p(v){if(v==null||v==="")return"—";v=Number(v);return Number.isFinite(v)?(v>0?"+":"")+v.toFixed(2).replace(".",",")+"%":"—"}
  function sym(v){var raw=String(v||"").split(":")[0],parts=raw.split("/");return parts.length>1?parts[0]+" / "+parts[1]:raw||"—"}
  function cls(v){return Number(v)>0?"positive":Number(v)<0?"negative":""}
  function dt(v){return v?new Date(v).toLocaleString("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"—"}
  var token=localStorage.getItem("tyee_admin_token")||"";
  document.querySelectorAll("[data-days]").forEach(function(b){b.onclick=function(){days=Number(b.dataset.days);document.querySelectorAll("[data-days]").forEach(function(x){x.classList.toggle("active",x===b)});render()}});
  document.querySelectorAll("[data-trade-range]").forEach(function(b){b.onclick=function(){tradeRange=b.dataset.tradeRange;document.querySelectorAll("[data-trade-range]").forEach(function(x){x.classList.toggle("active",x===b)});if(data&&data.latest){trades(data.latest);renderCopyAddon(data.latest.copy_trading)}}});
  function heartbeatWindow(q){var b=(q&&q.bot_status)||{},poll=Math.max(1,Number(b.poll_seconds||30));return Math.max(15000,poll*2500)}
  function setBotHealth(q){var box=e("botHealth"),label=e("botHealthLabel"),detail=e("botHealthDetail"),b=(q&&q.bot_status)||{},heartbeat=Number(b.heartbeat_at||(q&&q.received_at)||0),age=Date.now()-heartbeat,poll=Number(b.poll_seconds||30),active=Boolean(heartbeat)&&b.enabled!==false&&age<heartbeatWindow(q);box.classList.remove("waiting","active","passive");box.classList.add(active?"active":"passive");label.textContent=active?"BOT AKTİF":"BOT PASİF";detail.textContent=active?(String(b.mode||"paper").toUpperCase()+" · "+poll+" sn piyasa taraması"):(heartbeat?"Son veri "+Math.max(1,Math.round(age/1000))+" sn önce":"Canlı veri alınamıyor")}
  function updateTradingView(value){var market=String(value||"BTC/USDT:USDT").split(":")[0].replace("/",""),symbol="BINANCE:"+market;if(symbol===tradingViewSymbol)return;tradingViewSymbol=symbol;var mount=e("tradingviewMount");mount.innerHTML='<div class="tradingview-widget-container__widget"></div>';var script=document.createElement("script");script.type="text/javascript";script.src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js";script.async=true;script.text=JSON.stringify({autosize:true,symbol:symbol,interval:"5",timezone:"Europe/Istanbul",theme:"light",style:"1",locale:"tr",backgroundColor:"#ffffff",gridColor:"rgba(30, 41, 59, 0.08)",allow_symbol_change:false,calendar:false,details:false,hide_legend:false,hide_side_toolbar:true,hide_top_toolbar:false,hide_volume:false,hotlist:false,save_image:false,withdateranges:true,support_host:"https://www.tradingview.com"});mount.appendChild(script)}
  function syncChartSelection(q){var universe=Array.isArray(q.universe)?q.universe.slice():[],saved=localStorage.getItem("futures_lab_chart_symbol")||"",fallback=universe.indexOf("AVAX/USDT:USDT")>=0?"AVAX/USDT:USDT":(q.market_symbol||universe[0]||"BTC/USDT:USDT");if(!chartSelection)chartSelection=universe.indexOf(saved)>=0?saved:fallback;if(universe.indexOf(chartSelection)<0)universe.unshift(chartSelection);var select=e("chartCoinSelect"),signature=universe.join("|");if(select.dataset.signature!==signature){select.innerHTML=universe.map(function(symbol){return'<option value="'+esc(symbol)+'">'+esc(sym(symbol))+'</option>'}).join("");select.dataset.signature=signature}select.value=chartSelection;select.onchange=function(){chartSelection=select.value;localStorage.setItem("futures_lab_chart_symbol",chartSelection);updateTradingView(chartSelection);renderSelectedMarket(q)};updateTradingView(chartSelection)}
  function renderSelectedMarket(q){var rows=q.strategies||{},selectedPrice=null;if(q.market_symbol===chartSelection)selectedPrice=Number(q.market_price);Object.keys(rows).forEach(function(key){var row=rows[key]||{};if(row.symbol===chartSelection&&Number.isFinite(Number(row.mark_price)))selectedPrice=Number(row.mark_price)});var copy=q.copy_trading||q;(copy.positions||[]).forEach(function(row){if(row.symbol===chartSelection&&Number.isFinite(Number(row.mark_price)))selectedPrice=Number(row.mark_price)});e("marketSymbol").textContent=sym(chartSelection)+" Perpetual · sabit grafik";e("mainPrice").textContent=Number.isFinite(selectedPrice)?n(selectedPrice,4)+" $":"Canlı grafik";var matching=(data.history||[]).filter(function(item){return item.market_symbol===chartSelection&&Number.isFinite(Number(item.market_price))});var first=matching.length>1?Number(matching[0].market_price):null,change=first&&Number.isFinite(selectedPrice)?100*(selectedPrice/first-1):null;e("priceDelta").textContent=change==null?"":p(change);e("priceDelta").className=change==null?"":cls(change)}
  async function load(){try{var headers=token?{Authorization:"Bearer "+token}:{};var r=await fetch("/api/admin/avax-dashboard",{headers:headers,cache:"no-store"});if(r.status===401||r.status===403){location.href="/admin.html";return}if(r.ok){data=await r.json();render();return}setBotHealth(data&&data.latest)}catch(_){setBotHealth(data&&data.latest)}}
  function history(){var cutoff=Date.now()-days*86400000;return(data.history||[]).filter(function(x){return Number(x.market_candle)>=cutoff})}
  function render(){
    if(!data||!data.latest){e("cards").innerHTML='<article class="panel empty" style="grid-column:1/-1">Bot verisi bekleniyor. Render bağlantısı kurulduğunda panel otomatik dolacak.</article>';return}
    if(data.latest.mode==="hyperliquid_copy"){renderCopy();return}
    overview();activePositionsBoard();cards();trades(data.latest);periods(data.history||[]);renderCopyAddon(data.latest.copy_trading);
  }
  function shortWallet(v){v=String(v||"");return v.length>12?v.slice(0,6)+"…"+v.slice(-4):v}
  function renderCopy(){
    var q=data.latest,positions=Array.isArray(q.positions)?q.positions:[],wallets=q.wallets||{},age=Date.now()-Number((q.bot_status||{}).heartbeat_at||q.received_at||0),live=age<heartbeatWindow(q);
    setBotHealth(q);e("status").classList.toggle("live",live);e("status").querySelector("span").textContent=live?"Cüzdan akışı izleniyor":"Veri gecikmiş olabilir";e("updated").textContent="Son güncelleme "+dt(q.received_at);
    syncChartSelection(q);renderSelectedMarket(q);e("universeRule").textContent=esc(q.universe_size||"—")+" piyasa";e("pollRule").textContent=esc((q.bot_status||{}).poll_seconds||5)+" saniye";
    e("countdown").textContent=n(q.equity_usdt,2)+" $";e("experimentText").textContent="6.000 $ kopya kasası · anlık özsermaye";e("progressBar").style.width=Math.max(0,Math.min(100,Number(q.equity_usdt||0)/60))+"%";e("activePositions").textContent=positions.length;e("totalTrades").textContent=q.closed_trades||0;
    e("marketFlow").innerHTML=[["İşlem teminatı",n(q.margin_per_position,0)+" $"],["Pozisyon büyüklüğü",n(q.notional_per_position,0)+" $"],["Kaldıraç",esc(q.leverage)+"x"],["Kapasite",esc(positions.length)+" / "+esc(q.max_positions)]].map(function(x){return'<div class="flowItem"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join("");
    renderCopyPositions(positions);renderCopyWallets(wallets);copyTrades(q);copyPeriods(data.history||[]);
  }
  function renderCopyPositions(positions){
    var count=e("activePositionCount");count.textContent=positions.length+" açık";count.classList.toggle("hasPositions",positions.length>0);
    if(!positions.length){e("activePositionBoard").innerHTML='<div class="activePositionsEmpty"><div><strong>Yeni kaynak pozisyon bekleniyor</strong><span>Deploy anında açık işlemler kopyalanmadı; iki hesabın sonraki girişleri izleniyor.</span></div><i class="scanPulse"></i></div>';return}
    e("activePositionBoard").innerHTML=positions.map(function(s){var side=String(s.side||"").toLowerCase(),pnl=Number(s.position_pnl_usdt||0);return'<article class="activePositionCard '+side+'"><div class="activePositionTop"><div><div class="activeCoin">'+esc(sym(s.symbol))+'</div><span class="activeStrategy">'+esc(shortWallet(s.source))+' · Hyperliquid</span></div><span class="directionBadge '+side+'">'+esc(side.toUpperCase())+'</span></div><div class="activeResult"><div><span class="label">Anlık net kâr / zarar</span><div class="activePnl '+cls(pnl)+'">'+(pnl>0?"+":"")+n(pnl,2)+' $</div></div><div class="activeRoi"><strong class="'+cls(s.position_roi_pct)+'">'+p(s.position_roi_pct)+'</strong><span>Açık ROI</span></div></div><div class="activePositionMetrics"><div><span>Giriş</span><strong>'+n(s.entry,6)+' $</strong></div><div><span>Güncel</span><strong>'+n(s.mark_price,6)+' $</strong></div><div><span>Teminat</span><strong>'+n(s.remaining_margin,0)+' $</strong></div><div><span>Nominal</span><strong>'+n(s.notional,0)+' $</strong></div></div><div class="activeOpened"><b>'+dt(s.opened_at)+'</b> açıldı · kaynak azaltınca aynı oranda kapanır</div></article>'}).join("");
  }
  function renderCopyWallets(wallets){
    e("cards").innerHTML=Object.keys(wallets).map(function(address){var w=wallets[address]||{},total=Number(w.realized_pnl_usdt||0)+Number(w.unrealized_pnl_usdt||0);return'<article class="card"><div class="cardHead"><div><span class="label">Kaynak cüzdan</span><div class="name">'+esc(shortWallet(address))+'</div><div class="strategyExplain">Hyperliquid işlemleri gerçek zamanlı takip ediliyor.</div></div><span class="pill '+(w.open_positions?"long":"")+'">'+esc(w.open_positions||0)+' AÇIK</span></div><div class="roi '+cls(total)+'">'+(total>0?"+":"")+n(total,2)+' $</div><span class="label">Bizde oluşan toplam sonuç</span><div class="metrics"><div class="metric"><span class="label">Kapanan</span><strong>'+esc(w.closed_trades||0)+'</strong></div><div class="metric"><span class="label">Başarı</span><strong>'+p(w.win_rate_pct)+'</strong></div><div class="metric"><span class="label">Açık PNL</span><strong class="'+cls(w.unrealized_pnl_usdt)+'">'+n(w.unrealized_pnl_usdt,2)+' $</strong></div></div><a class="coinBadge" target="_blank" rel="noopener noreferrer" href="https://hyperstats.org/wallet/'+encodeURIComponent(address)+'?tab=history">HyperStats geçmişini aç ↗</a></article>'}).join("");
  }
  function copyTrades(q){
    var cutoff=tradeRangeStart(tradeRange),rows=(q.recent_trades||[]).filter(function(t){return Number(t.closed_at)>=cutoff}).sort(function(a,b){return Number(b.closed_at)-Number(a.closed_at)});
    if(!rows.length){e("trades").innerHTML='<div class="empty">Seçilen dönemde kapanan kopya işlem yok.</div>';return}
    e("trades").innerHTML='<table><thead><tr><th>Kaynak</th><th>Coin</th><th>Yön</th><th>Pozisyon</th><th>Net K/Z</th><th>ROI</th><th>Kapanış</th><th>Zaman</th></tr></thead><tbody>'+rows.map(function(t){return'<tr><td>'+esc(shortWallet(t.source))+'</td><td>'+esc(sym(t.symbol))+'</td><td>'+esc(String(t.side||"").toUpperCase())+'</td><td>'+n(Number(t.entry)*Number(t.quantity),2)+' $</td><td class="'+cls(t.net_pnl)+'">'+(Number(t.net_pnl)>0?"+":"")+n(t.net_pnl,2)+' $</td><td class="'+cls(t.roi_pct)+'">'+p(t.roi_pct)+'</td><td>'+esc(t.exit_reason||"—")+'</td><td>'+dt(t.closed_at)+'</td></tr>'}).join("")+'</tbody></table>';
  }
  function copyPeriods(h){
    var rows=h.filter(function(q){return q.mode==="hyperliquid_copy"}),grouped={};rows.forEach(function(q){var key=new Date(q.market_candle).toISOString().slice(0,10);if(!grouped[key])grouped[key]={first:q,last:q};else grouped[key].last=q});var keys=Object.keys(grouped).sort().reverse().slice(0,7);
    if(!keys.length){e("periods").innerHTML='<div class="empty">Dönem verisi bekleniyor</div>';return}
    e("periods").innerHTML='<div class="period head"><span>Gün</span><span>Kasa ROI</span><span>Gerçekleşen</span><span>Açık PNL</span></div>'+keys.map(function(key){var x=grouped[key],roi=Number(x.last.wallet_roi_pct||0)-Number(x.first.wallet_roi_pct||0);return'<div class="period"><span>'+key+'</span><span class="'+cls(roi)+'">'+p(roi)+'</span><span class="'+cls(x.last.realized_pnl_usdt)+'">'+n(x.last.realized_pnl_usdt,2)+' $</span><span class="'+cls(x.last.unrealized_pnl_usdt)+'">'+n(x.last.unrealized_pnl_usdt,2)+' $</span></div>'}).join("");
  }
  function renderCopyAddon(q){
    if(!e("copySummary"))return;
    if(!q){e("copyHealth").textContent="2 CÜZDAN · VERİ BEKLENİYOR";e("copySummary").innerHTML=[["Sanal kasa","6.000 $"],["İşlem teminatı","600 $ · %10"],["Pozisyon","1.200 $ · 2x"],["Kaynak","2 cüzdan"]].map(function(x){return'<div class="flowItem"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join("");e("copyPositionBoard").innerHTML='<div class="activePositionsEmpty"><div><strong>İki kaynak cüzdan izleniyor</strong><span>Hyperliquid bağlantısı yenilenirken mevcut strateji sistemi çalışmaya devam ediyor.</span></div><i class="scanPulse"></i></div>';e("copyWalletCards").innerHTML=copyWalletAddresses.map(function(address){return'<article class="card"><div class="cardHead"><div><span class="label">Kaynak cüzdan</span><div class="name">'+esc(shortWallet(address))+'</div><div class="strategyExplain">Stratejilerden bağımsız izlenir.</div></div><span class="pill">BAĞLANIYOR</span></div><div class="roi">—</div><span class="label">Kopya kasasında veri bekleniyor</span><a class="coinBadge" target="_blank" rel="noopener noreferrer" href="https://hyperstats.org/wallet/'+encodeURIComponent(address)+'?tab=history">HyperStats geçmişini aç ↗</a></article>'}).join("");e("copyTradeTable").innerHTML='<div class="empty">Kopya verisi bekleniyor.</div>';return}
    var positions=Array.isArray(q.positions)?q.positions:[],wallets=q.wallets||{},heartbeat=Number((q.bot_status||{}).heartbeat_at||0),active=heartbeat&&Date.now()-heartbeat<heartbeatWindow(q);
    e("copyHealth").textContent=active?"KOPYA AKTİF":"KOPYA GECİKMİŞ";
    e("copyHealth").classList.toggle("hasPositions",active);
    e("copySummary").innerHTML=[["Sanal kasa",n(q.equity_usdt,2)+" $"],["İşlem teminatı",n(q.margin_per_position,0)+" $ · %10"],["Pozisyon",n(q.notional_per_position,0)+" $ · 2x"],["Kapasite",positions.length+" / "+esc(q.max_positions)],["Kaynak","2 cüzdan"],["Başlangıç filtresi",esc(q.ignored_existing_positions||0)+" işlem atlandı"]].map(function(x){return'<div class="flowItem"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join("");
    if(!positions.length)e("copyPositionBoard").innerHTML='<div class="activePositionsEmpty"><div><strong>Yeni kaynak pozisyon bekleniyor</strong><span>Mevcut stratejiler ayrı kasalarında işlem aramaya devam ediyor.</span></div><i class="scanPulse"></i></div>';
    else e("copyPositionBoard").innerHTML=positions.map(function(s){var side=String(s.side||"").toLowerCase(),pnl=Number(s.position_pnl_usdt||0);return'<article class="activePositionCard '+side+'"><div class="activePositionTop"><div><div class="activeCoin">'+esc(sym(s.symbol))+'</div><span class="activeStrategy">'+esc(shortWallet(s.source))+' · Hyperliquid kopya</span></div><span class="directionBadge '+side+'">'+esc(side.toUpperCase())+'</span></div><div class="activeResult"><div><span class="label">Anlık net kâr / zarar</span><div class="activePnl '+cls(pnl)+'">'+(pnl>0?"+":"")+n(pnl,2)+' $</div></div><div class="activeRoi"><strong class="'+cls(s.position_roi_pct)+'">'+p(s.position_roi_pct)+'</strong><span>Açık ROI</span></div></div><div class="activePositionMetrics"><div><span>Giriş</span><strong>'+n(s.entry,6)+' $</strong></div><div><span>Güncel</span><strong>'+n(s.mark_price,6)+' $</strong></div><div><span>Teminat</span><strong>'+n(s.remaining_margin,0)+' $</strong></div><div><span>Nominal</span><strong>'+n(s.notional,0)+' $</strong></div></div></article>'}).join("");
    e("copyWalletCards").innerHTML=Object.keys(wallets).map(function(address){var w=wallets[address]||{},total=Number(w.realized_pnl_usdt||0)+Number(w.unrealized_pnl_usdt||0);return'<article class="card"><div class="cardHead"><div><span class="label">Kaynak cüzdan</span><div class="name">'+esc(shortWallet(address))+'</div><div class="strategyExplain">Stratejilerden bağımsız izlenir.</div></div><span class="pill '+(w.open_positions?"long":"")+'">'+esc(w.open_positions||0)+' AÇIK</span></div><div class="roi '+cls(total)+'">'+(total>0?"+":"")+n(total,2)+' $</div><span class="label">Kopya kasasında toplam sonuç</span><div class="metrics"><div class="metric"><span class="label">Kapanan</span><strong>'+esc(w.closed_trades||0)+'</strong></div><div class="metric"><span class="label">Başarı</span><strong>'+p(w.win_rate_pct)+'</strong></div><div class="metric"><span class="label">Açık PNL</span><strong class="'+cls(w.unrealized_pnl_usdt)+'">'+n(w.unrealized_pnl_usdt,2)+' $</strong></div></div><a class="coinBadge" target="_blank" rel="noopener noreferrer" href="https://hyperstats.org/wallet/'+encodeURIComponent(address)+'?tab=history">HyperStats geçmişini aç ↗</a></article>'}).join("");
    var cutoff=tradeRangeStart(tradeRange),rows=(q.recent_trades||[]).filter(function(t){return Number(t.closed_at)>=cutoff}).sort(function(a,b){return Number(b.closed_at)-Number(a.closed_at)});
    e("copyTradeTable").innerHTML=rows.length?'<table><thead><tr><th>Kaynak</th><th>Coin</th><th>Yön</th><th>Pozisyon</th><th>Net K/Z</th><th>ROI</th><th>Kapanış</th><th>Zaman</th></tr></thead><tbody>'+rows.map(function(t){return'<tr><td>'+esc(shortWallet(t.source))+'</td><td>'+esc(sym(t.symbol))+'</td><td>'+esc(String(t.side||"").toUpperCase())+'</td><td>'+n(Number(t.entry)*Number(t.quantity),2)+' $</td><td class="'+cls(t.net_pnl)+'">'+(Number(t.net_pnl)>0?"+":"")+n(t.net_pnl,2)+' $</td><td class="'+cls(t.roi_pct)+'">'+p(t.roi_pct)+'</td><td>'+esc(t.exit_reason||"—")+'</td><td>'+dt(t.closed_at)+'</td></tr>'}).join("")+'</tbody></table>':'<div class="empty">Seçilen dönemde kapanan kopya işlem yok.</div>';
  }
  function overview(){
    var q=data.latest,age=Date.now()-Number((q.bot_status||{}).heartbeat_at||q.received_at||0),live=age<heartbeatWindow(q),rows=q.strategies||{},keys=Object.keys(labels);setBotHealth(q);
    e("status").classList.toggle("live",live);e("status").querySelector("span").textContent=q.continuous?(live?"Canlı veri akışı":"Veri gecikmiş olabilir"):(q.finalized_at?"Deney tamamlandı":live?"Canlı veri akışı":"Veri gecikmiş olabilir");
    e("updated").textContent="Son güncelleme "+dt(q.received_at);
    syncChartSelection(q);
    renderSelectedMarket(q);
    e("universeRule").textContent=esc(q.universe_size||50)+" coin";
    e("pollRule").textContent=esc((q.bot_status||{}).strategy_poll_seconds||30)+" saniye";
    var remaining=Math.max(0,Number(q.ends_at)-Date.now()),hours=Math.floor(remaining/3600000),mins=Math.floor(remaining%3600000/60000);
    e("countdown").textContent=q.continuous?"Sürekli aktif":q.finalized_at?"Tamamlandı":hours+"sa "+mins+"dk";
    e("experimentText").textContent=q.continuous?"Saat sınırı yok · sonuçlar kesintisiz birikir":q.finalized_at?"Sonuçlar donduruldu.":"Deney bitimine kalan süre";
    var duration=Math.max(1,Number(q.ends_at)-Number(q.started_at)),progress=q.continuous?100:Math.max(0,Math.min(100,100*(Date.now()-Number(q.started_at))/duration));e("progressBar").style.width=progress+"%";
    var active=keys.filter(function(k){return rows[k]&&rows[k].position}).length,total=keys.reduce(function(s,k){return s+Number((rows[k]||{}).trades||0)},0);e("activePositions").textContent=active;e("totalTrades").textContent=total;
    var c=q.market_context||{};var flow=[["Açık pozisyon 1s",p(c.open_interest_change_pct_1h)],["Taker al/sat",n(c.taker_buy_sell_ratio_1h,2)],["Genel long/short",n(c.global_long_short_ratio,2)],["Fonlama",p(Number(c.funding_rate||0)*100)]];
    e("marketFlow").innerHTML=flow.map(function(x){return'<div class="flowItem"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join("");
  }
  function activePositionsBoard(){
    var rows=data.latest.strategies||{},active=Object.keys(labels).filter(function(k){return rows[k]&&rows[k].position}),count=e("activePositionCount");count.textContent=active.length+" açık";count.classList.toggle("hasPositions",active.length>0);
    if(!active.length){e("activePositionBoard").innerHTML='<div class="activePositionsEmpty"><div><strong>Şu anda açık pozisyon yok</strong><span>Beş strateji, en likit 50 coinde kendi giriş koşulunu bekliyor.</span></div><i class="scanPulse"></i></div>';return}
    e("activePositionBoard").innerHTML=active.map(function(k){var s=rows[k],side=String(s.position).toLowerCase(),pnl=s.position_pnl_usdt;if(pnl==null&&s.equity_usdt!=null&&s.realized_balance_usdt!=null)pnl=Number(s.equity_usdt)-Number(s.realized_balance_usdt);return'<article class="activePositionCard '+side+'"><div class="activePositionTop"><div><div class="activeCoin">'+esc(sym(s.symbol))+'</div><span class="activeStrategy">'+esc(labels[k])+' · Kural '+esc(s.rule_version||"ESKİ")+'</span></div><span class="directionBadge '+side+'">'+esc(side.toUpperCase())+'</span></div><div class="activeResult"><div><span class="label">Anlık net kâr / zarar</span><div class="activePnl '+cls(pnl)+'">'+(Number(pnl)>0?"+":"")+n(pnl,4)+' $</div></div><div class="activeRoi"><strong class="'+cls(s.position_roi_pct)+'">'+p(s.position_roi_pct)+'</strong><span>Açık ROI</span></div></div><div class="activePositionMetrics"><div><span>Giriş</span><strong>'+n(s.entry,4)+' $</strong></div><div><span>Güncel</span><strong>'+n(s.mark_price,4)+' $</strong></div><div><span>Stop</span><strong class="negative">'+n(s.stop,4)+' $</strong></div><div><span>Hedef</span><strong class="positive">'+n(s.take,4)+' $</strong></div></div><div class="activeOpened"><b>'+dt(s.opened_at)+'</b> açıldı · '+esc(s.reason||"Strateji koşulları oluştu")+'</div></article>'}).join("");
  }
  function adaptationHtml(s){
    var a=s.adaptation||{},params=a.parameters||{},parts=[];
    if(params.atr_stop_multiplier!=null)parts.push("ATR stop "+n(params.atr_stop_multiplier,1)+"x");
    if(params.cooldown_ms!=null)parts.push("Bekleme "+Math.round(Number(params.cooldown_ms)/60000)+" dk");
    if(params.entry_band_zone_fraction!=null)parts.push("Band bölgesi %"+n(Number(params.entry_band_zone_fraction)*100,0));
    return'<div class="adaptationBox"><div class="adaptationTop"><strong>Öz değerlendirme · Nesil '+esc(a.generation||0)+'</strong></div><p>'+esc(a.diagnosis||"İşlem verisi birikiyor.")+'</p><div class="adaptationParams">'+parts.map(function(x){return"<span>"+esc(x)+"</span>"}).join("")+'<span>Sonraki inceleme: '+esc(a.next_review_after_trades==null?5:a.next_review_after_trades)+' işlem</span></div></div>';
  }
  function cards(){
    var q=data.latest;e("cards").innerHTML=Object.keys(labels).map(function(k){var s=q.strategies[k]||{},pos=s.position,risk=s.risk_status||{},stateText=pos?String(pos).toUpperCase():(risk.halted?"RİSK DURDURDU":"SİNYAL BEKLİYOR"),stateClass=pos|| (risk.halted?"halted":"");return'<article class="card"><div class="cardHead"><div><span class="label">Strateji</span><div class="name">'+labels[k]+'</div><div class="strategyExplain">'+explain[k]+'</div></div><span class="pill '+stateClass+'">'+stateText+'</span></div>'+(pos?'<div class="coinBadge">'+esc(sym(s.symbol))+'</div>':'')+'<div class="roi '+cls(s.wallet_roi_pct)+'">'+p(s.wallet_roi_pct)+'</div><span class="label">Toplam cüzdan ROI · komisyon dahil</span><div class="metrics"><div class="metric"><span class="label">Açık ROI</span><strong class="'+cls(s.position_roi_pct)+'">'+p(s.position_roi_pct)+'</strong></div><div class="metric"><span class="label">İşlem</span><strong>'+esc(s.trades||0)+'</strong></div><div class="metric"><span class="label">Başarı</span><strong>'+p(s.win_rate_pct)+'</strong></div><div class="metric"><span class="label">Sanal bakiye</span><strong>'+n(s.equity_usdt,2)+' $</strong></div><div class="metric"><span class="label">En kötü düşüş</span><strong>'+p(-Math.abs(Number(s.max_drawdown_pct||0)))+'</strong></div><div class="metric"><span class="label">Hedef ROE</span><strong class="positive">'+p(s.take_profit_roe_pct)+'</strong></div></div>'+adaptationHtml(s)+(pos?'<div class="position"><span class="label">Açık pozisyon ayrıntısı</span><div class="positionGrid"><div><span>Coin</span><strong>'+esc(sym(s.symbol))+'</strong></div><div><span>Yön</span><strong class="'+(pos==="long"?"positive":"negative")+'">'+String(pos).toUpperCase()+'</strong></div><div><span>Giriş</span><strong>'+n(s.entry,4)+'</strong></div><div><span>Güncel</span><strong>'+n(s.mark_price,4)+'</strong></div><div><span>Stop</span><strong class="negative">'+n(s.stop,4)+'</strong></div><div><span>Kâr hedefi</span><strong class="positive">'+n(s.take,4)+'</strong></div><div><span>Neden açtı?</span><strong>'+esc(s.reason||"—")+'</strong></div></div></div>':'<div class="position empty">'+(risk.halted?"Yeni işlem güvenlik nedeniyle durduruldu · "+esc(risk.reason||"risk limiti"):"50 coin taranıyor · uygun giriş noktası bekleniyor")+'</div>')+'</article>'}).join("");
  }
  function selectors(){e("strategySelector").innerHTML=Object.keys(labels).map(function(k){return'<button data-strategy="'+k+'" class="'+(k===selected?"active":"")+'">'+labels[k].split(" ")[0]+'</button>'}).join("");e("strategySelector").querySelectorAll("button").forEach(function(b){b.onclick=function(){selected=b.dataset.strategy;selectors();marketChart(history())}})}
  function setup(id){var c=e(id),r=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*r;c.height=h*r;var x=c.getContext("2d");x.scale(r,r);x.clearRect(0,0,w,h);return{c:c,x:x,w:w,h:h,pad:30}}
  function grid(g,lo,hi){var x=g.x,w=g.w,h=g.h,pad=g.pad;x.strokeStyle="#20332d";x.lineWidth=1;for(var i=0;i<4;i++){var y=pad+(h-pad*2)*i/3;x.beginPath();x.moveTo(pad,y);x.lineTo(w-pad,y);x.stroke()}x.fillStyle="#8da39b";x.font="10px system-ui";x.fillText(hi.toFixed(2),3,12);x.fillText(lo.toFixed(2),3,h-5)}
  function spark(h){var g=setup("priceSpark"),vs=h.map(function(q){return Number(q.market_price)}).filter(Number.isFinite);if(vs.length<2)return;var lo=Math.min.apply(null,vs),hi=Math.max.apply(null,vs);if(hi===lo){hi++;lo--}var grad=g.x.createLinearGradient(0,0,0,g.h);grad.addColorStop(0,"#52e1a055");grad.addColorStop(1,"#52e1a000");g.x.beginPath();vs.forEach(function(v,i){var px=i*g.w/(vs.length-1),py=g.h-4-(v-lo)/(hi-lo)*(g.h-12);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.lineTo(g.w,g.h);g.x.lineTo(0,g.h);g.x.closePath();g.x.fillStyle=grad;g.x.fill();g.x.beginPath();vs.forEach(function(v,i){var px=i*g.w/(vs.length-1),py=g.h-4-(v-lo)/(hi-lo)*(g.h-12);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.strokeStyle="#52e1a0";g.x.lineWidth=2;g.x.stroke()}
  function marketChart(h){var g=setup("marketChart"),s=(data.latest.strategies||{})[selected]||{},vs=h.map(function(q){return Number(((q.strategies||{})[selected]||{}).mark_price)}).filter(Number.isFinite),symbol=sym(s.symbol);e("riskSymbol").textContent=symbol;e("riskTitle").textContent=symbol+" · giriş / stop / hedef";if(vs.length<2){g.x.fillStyle="#8da39b";g.x.fillText(s.position?"Fiyat grafiği için veri birikiyor":"Bu stratejide açık pozisyon yok",18,28);return}var levels=[s.entry,s.stop,s.take].map(Number).filter(Number.isFinite),lo=Math.min.apply(null,vs.concat(levels)),hi=Math.max.apply(null,vs.concat(levels));if(hi===lo){hi++;lo--}grid(g,lo,hi);function y(v){return g.h-g.pad-(v-lo)/(hi-lo)*(g.h-g.pad*2)}g.x.beginPath();vs.forEach(function(v,i){var px=g.pad+(g.w-g.pad*2)*i/(vs.length-1),py=y(v);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.strokeStyle="#edf7f2";g.x.lineWidth=2;g.x.stroke();[[s.entry,"#6da7ff","Giriş"],[s.stop,"#ff7380","Stop"],[s.take,"#52e1a0","Hedef"]].forEach(function(a){var v=Number(a[0]);if(!Number.isFinite(v))return;var py=y(v);g.x.setLineDash([6,5]);g.x.strokeStyle=a[1];g.x.beginPath();g.x.moveTo(g.pad,py);g.x.lineTo(g.w-g.pad,py);g.x.stroke();g.x.setLineDash([]);g.x.fillStyle=a[1];g.x.fillText(a[2]+" "+v.toFixed(4),g.pad+4,py-5)})}
  function multiChart(id,h,key,negative){var g=setup(id);if(h.length<2){g.x.fillStyle="#8da39b";g.x.fillText("Grafik için veri birikiyor",18,28);return}var vs=[];h.forEach(function(q){Object.keys(labels).forEach(function(k){var v=Number((q.strategies[k]||{})[key]||0);vs.push(negative?-Math.abs(v):v)})});var lo=Math.min.apply(null,vs.concat([0])),hi=Math.max.apply(null,vs.concat([0]));if(hi===lo){hi++;lo--}grid(g,lo,hi);Object.keys(labels).forEach(function(k){g.x.strokeStyle=colors[k];g.x.lineWidth=2;g.x.beginPath();h.forEach(function(q,i){var v=Number((q.strategies[k]||{})[key]||0);if(negative)v=-Math.abs(v);var px=g.pad+(g.w-g.pad*2)*i/(h.length-1),py=g.h-g.pad-(v-lo)/(hi-lo)*(g.h-g.pad*2);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.stroke()})}
  function tradeRangeStart(kind){var d=new Date();if(kind==="month"){d.setDate(1);d.setHours(0,0,0,0);return d.getTime()}if(kind==="week")d.setDate(d.getDate()-6);d.setHours(0,0,0,0);return d.getTime()}
  function trades(q){var rows=[],cutoff=tradeRangeStart(tradeRange),ledger=data.closed_trades||{};Object.keys(labels).forEach(function(k){var saved=Array.isArray(ledger[k])?ledger[k]:((q.strategies[k]||{}).recent_trades||[]);saved.forEach(function(t){if(Number(t.closed_at)>=cutoff)rows.push({k:k,t:t})})});rows.sort(function(a,b){return Number(b.t.closed_at)-Number(a.t.closed_at)});if(!rows.length){e("trades").innerHTML='<div class="empty">Seçilen dönemde kapanan işlem yok.</div>';return}e("trades").innerHTML='<table><thead><tr><th>Strateji</th><th>Kural</th><th>Coin</th><th>Yön</th><th>Pozisyon</th><th>Giriş</th><th>Çıkış</th><th>Net K/Z</th><th>ROI</th><th>Neden kapandı?</th><th>Zaman</th></tr></thead><tbody>'+rows.map(function(r){var notional=Number(r.t.entry)*Number(r.t.quantity);return'<tr><td>'+labels[r.k]+'</td><td>'+esc(r.t.rule_version||"ESKİ")+'</td><td>'+esc(sym(r.t.symbol))+'</td><td>'+esc(String(r.t.side||"").toUpperCase())+'</td><td>'+n(notional,2)+' $</td><td>'+n(r.t.entry,4)+'</td><td>'+n(r.t.exit,4)+'</td><td class="'+cls(r.t.net_pnl)+'">'+(Number(r.t.net_pnl)>0?"+":"")+n(r.t.net_pnl,2)+' $</td><td class="'+cls(r.t.roi_pct)+'">'+p(r.t.roi_pct)+'</td><td>'+esc(r.t.exit_reason||"—")+'</td><td>'+dt(r.t.closed_at)+'</td></tr>'}).join("")+'</tbody></table>'}
  function periods(h){if(!h.length){e("periods").innerHTML='<div class="empty">Dönem verisi bekleniyor</div>';return}function week(ms){var d=new Date(ms),shift=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-shift);return d.toISOString().slice(0,10)}function grouped(kind){var g={};h.forEach(function(q){var k=kind==="Gün"?new Date(q.market_candle).toISOString().slice(0,10):week(q.market_candle);if(!g[k])g[k]={first:q,last:q};else g[k].last=q});return Object.keys(g).sort().reverse().slice(0,kind==="Gün"?7:6).map(function(k){return{label:(kind==="Gün"?"G ":"H ")+k,pair:g[k]}})}function delta(row,s){return Number((row.pair.last.strategies[s]||{}).wallet_roi_pct||0)-Number((row.pair.first.strategies[s]||{}).wallet_roi_pct||0)}var rows=grouped("Gün").concat(grouped("Hafta")),keys=Object.keys(labels);e("periods").innerHTML='<div class="period head"><span>Dönem</span>'+keys.map(function(k){return"<span>"+labels[k].split(" ")[0]+"</span>"}).join("")+'</div>'+rows.map(function(r){return'<div class="period"><span>'+r.label+'</span>'+keys.map(function(s){var v=delta(r,s);return'<span class="'+cls(v)+'">'+p(v)+'</span>'}).join("")+'</div>'}).join("")}
  window.addEventListener("resize",function(){if(data)render()});load();setInterval(load,5000);
})();
