(function(){
  var labels={trend_breakout:"Trend kırılımı",pullback_reclaim:"Geri çekilme",liquidity_sweep:"Likidite süpürmesi"};
  var explain={trend_breakout:"Güçlü hacimle kırılan trendin devamını takip eder.",pullback_reclaim:"Trend içinde fiyatın sakinleşip yeniden güçlenmesini bekler.",liquidity_sweep:"Sahte kırılım ve stop avı sonrasındaki dönüşü arar."};
  var colors={trend_breakout:"#52e1a0",pullback_reclaim:"#64cddd",liquidity_sweep:"#f1b95f"};
  var days=7,data=null,selected="trend_breakout";
  function e(id){return document.getElementById(id)}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})}
  function n(v,d){if(v==null||v==="")return"—";v=Number(v);return Number.isFinite(v)?v.toLocaleString("tr-TR",{minimumFractionDigits:d==null?2:d,maximumFractionDigits:d==null?2:d}):"—"}
  function p(v){if(v==null||v==="")return"—";v=Number(v);return Number.isFinite(v)?(v>0?"+":"")+v.toFixed(2).replace(".",",")+"%":"—"}
  function cls(v){return Number(v)>0?"positive":Number(v)<0?"negative":""}
  function dt(v){return v?new Date(v).toLocaleString("tr-TR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"—"}
  var token=localStorage.getItem("tyee_admin_token")||"";
  document.querySelectorAll("[data-days]").forEach(function(b){b.onclick=function(){days=Number(b.dataset.days);document.querySelectorAll("[data-days]").forEach(function(x){x.classList.toggle("active",x===b)});render()}});
  async function load(){var headers=token?{Authorization:"Bearer "+token}:{};var r=await fetch("/api/admin/avax-dashboard",{headers:headers});if(r.status===401||r.status===403){location.href="/admin.html";return}if(r.ok){data=await r.json();render()}}
  function history(){var cutoff=Date.now()-days*86400000;return(data.history||[]).filter(function(x){return Number(x.market_candle)>=cutoff})}
  function render(){
    if(!data||!data.latest){e("cards").innerHTML='<article class="panel empty" style="grid-column:1/-1">Bot verisi bekleniyor. Render bağlantısı kurulduğunda panel otomatik dolacak.</article>';return}
    overview();cards();selectors();var h=history();marketChart(h);multiChart("roiChart",h,"wallet_roi_pct",false);multiChart("winChart",h,"win_rate_pct",false);multiChart("drawdownChart",h,"max_drawdown_pct",true);trades(data.latest);periods(data.history||[]);
  }
  function overview(){
    var q=data.latest,age=Date.now()-Number(q.received_at||0),live=age<20*60*1000,rows=q.strategies||{},keys=Object.keys(labels);
    e("status").classList.toggle("live",live);e("status").querySelector("span").textContent=q.finalized_at?"Deney tamamlandı":live?"Canlı veri akışı":"Veri gecikmiş olabilir";
    e("updated").textContent="Son güncelleme "+dt(q.received_at);
    e("mainPrice").textContent=n(q.market_price,4)+" $";
    var all=data.history||[],first=all.length?Number(all[Math.max(0,all.length-97)].market_price):Number(q.market_price),change=first?100*(Number(q.market_price)/first-1):0;
    e("priceDelta").textContent=p(change);e("priceDelta").className=cls(change);
    var remaining=Math.max(0,Number(q.ends_at)-Date.now()),hours=Math.floor(remaining/3600000),mins=Math.floor(remaining%3600000/60000);
    e("countdown").textContent=q.finalized_at?"Tamamlandı":hours+"sa "+mins+"dk";
    e("experimentText").textContent=q.finalized_at?"Sonuçlar donduruldu.":"Deney bitimine kalan süre";
    var duration=Math.max(1,Number(q.ends_at)-Number(q.started_at)),progress=Math.max(0,Math.min(100,100*(Date.now()-Number(q.started_at))/duration));e("progressBar").style.width=progress+"%";
    var active=keys.filter(function(k){return rows[k]&&rows[k].position}).length,total=keys.reduce(function(s,k){return s+Number((rows[k]||{}).trades||0)},0);e("activePositions").textContent=active;e("totalTrades").textContent=total;
    var ranked=keys.map(function(k){return{k:k,roi:Number((rows[k]||{}).wallet_roi_pct||0),trades:Number((rows[k]||{}).trades||0)}}).sort(function(a,b){return b.roi-a.roi});
    e("leaderName").textContent=labels[ranked[0].k];e("leaderRoi").textContent=p(ranked[0].roi);e("leaderRoi").className="leaderRoi "+cls(ranked[0].roi);e("leaderNote").textContent=ranked[0].trades?"Şimdilik en yüksek cüzdan getirisi.":"Henüz kapanan işlem yok; açık ROI değişebilir.";
    var c=q.market_context||{};var flow=[["Açık pozisyon 1s",p(c.open_interest_change_pct_1h)],["Taker al/sat",n(c.taker_buy_sell_ratio_1h,2)],["Genel long/short",n(c.global_long_short_ratio,2)],["Fonlama",p(Number(c.funding_rate||0)*100)]];
    e("marketFlow").innerHTML=flow.map(function(x){return'<div class="flowItem"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join("");
  }
  function cards(){
    var q=data.latest;e("cards").innerHTML=Object.keys(labels).map(function(k){var s=q.strategies[k]||{},pos=s.position;return'<article class="card"><div class="cardHead"><div><span class="label">Strateji</span><div class="name">'+labels[k]+'</div><div class="strategyExplain">'+explain[k]+'</div></div><span class="pill '+(pos||"")+'">'+(pos?String(pos).toUpperCase():"SİNYAL BEKLİYOR")+'</span></div><div class="roi '+cls(s.wallet_roi_pct)+'">'+p(s.wallet_roi_pct)+'</div><span class="label">Toplam cüzdan ROI · komisyon dahil</span><div class="metrics"><div class="metric"><span class="label">Açık ROI</span><strong class="'+cls(s.position_roi_pct)+'">'+p(s.position_roi_pct)+'</strong></div><div class="metric"><span class="label">İşlem</span><strong>'+esc(s.trades||0)+'</strong></div><div class="metric"><span class="label">Başarı</span><strong>'+p(s.win_rate_pct)+'</strong></div><div class="metric"><span class="label">Sanal bakiye</span><strong>'+n(s.equity_usdt,2)+' $</strong></div><div class="metric"><span class="label">En kötü düşüş</span><strong>'+p(-Math.abs(Number(s.max_drawdown_pct||0)))+'</strong></div><div class="metric"><span class="label">Kâr faktörü</span><strong>'+n(s.profit_factor,2)+'</strong></div></div>'+(pos?'<div class="position"><span class="label">Açık pozisyon ayrıntısı</span><div class="positionGrid"><div><span>Yön</span><strong class="'+(pos==="long"?"positive":"negative")+'">'+String(pos).toUpperCase()+'</strong></div><div><span>Giriş</span><strong>'+n(s.entry,4)+'</strong></div><div><span>Güncel</span><strong>'+n(s.mark_price,4)+'</strong></div><div><span>Stop</span><strong class="negative">'+n(s.stop,4)+'</strong></div><div><span>Kâr hedefi</span><strong class="positive">'+n(s.take,4)+'</strong></div><div><span>Neden açtı?</span><strong>'+esc(s.reason||"—")+'</strong></div></div></div>':'<div class="position empty">Pozisyon yok · uygun giriş noktası bekleniyor</div>')+'</article>'}).join("");
  }
  function selectors(){e("strategySelector").innerHTML=Object.keys(labels).map(function(k){return'<button data-strategy="'+k+'" class="'+(k===selected?"active":"")+'">'+labels[k].split(" ")[0]+'</button>'}).join("");e("strategySelector").querySelectorAll("button").forEach(function(b){b.onclick=function(){selected=b.dataset.strategy;selectors();marketChart(history())}})}
  function setup(id){var c=e(id),r=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*r;c.height=h*r;var x=c.getContext("2d");x.scale(r,r);x.clearRect(0,0,w,h);return{c:c,x:x,w:w,h:h,pad:30}}
  function grid(g,lo,hi){var x=g.x,w=g.w,h=g.h,pad=g.pad;x.strokeStyle="#20332d";x.lineWidth=1;for(var i=0;i<4;i++){var y=pad+(h-pad*2)*i/3;x.beginPath();x.moveTo(pad,y);x.lineTo(w-pad,y);x.stroke()}x.fillStyle="#8da39b";x.font="10px system-ui";x.fillText(hi.toFixed(2),3,12);x.fillText(lo.toFixed(2),3,h-5)}
  function spark(h){var g=setup("priceSpark"),vs=h.map(function(q){return Number(q.market_price)}).filter(Number.isFinite);if(vs.length<2)return;var lo=Math.min.apply(null,vs),hi=Math.max.apply(null,vs);if(hi===lo){hi++;lo--}var grad=g.x.createLinearGradient(0,0,0,g.h);grad.addColorStop(0,"#52e1a055");grad.addColorStop(1,"#52e1a000");g.x.beginPath();vs.forEach(function(v,i){var px=i*g.w/(vs.length-1),py=g.h-4-(v-lo)/(hi-lo)*(g.h-12);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.lineTo(g.w,g.h);g.x.lineTo(0,g.h);g.x.closePath();g.x.fillStyle=grad;g.x.fill();g.x.beginPath();vs.forEach(function(v,i){var px=i*g.w/(vs.length-1),py=g.h-4-(v-lo)/(hi-lo)*(g.h-12);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.strokeStyle="#52e1a0";g.x.lineWidth=2;g.x.stroke()}
  function marketChart(h){var g=setup("marketChart"),vs=h.map(function(q){return Number((q.market_ohlc||{}).close||q.market_price)}).filter(Number.isFinite),s=(data.latest.strategies||{})[selected]||{};if(vs.length<2){g.x.fillStyle="#8da39b";g.x.fillText("Fiyat grafiği için veri birikiyor",18,28);return}var levels=[s.entry,s.stop,s.take].map(Number).filter(Number.isFinite),lo=Math.min.apply(null,vs.concat(levels)),hi=Math.max.apply(null,vs.concat(levels));if(hi===lo){hi++;lo--}grid(g,lo,hi);function y(v){return g.h-g.pad-(v-lo)/(hi-lo)*(g.h-g.pad*2)}g.x.beginPath();vs.forEach(function(v,i){var px=g.pad+(g.w-g.pad*2)*i/(vs.length-1),py=y(v);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.strokeStyle="#edf7f2";g.x.lineWidth=2;g.x.stroke();[[s.entry,"#6da7ff","Giriş"],[s.stop,"#ff7380","Stop"],[s.take,"#52e1a0","Hedef"]].forEach(function(a){var v=Number(a[0]);if(!Number.isFinite(v))return;var py=y(v);g.x.setLineDash([6,5]);g.x.strokeStyle=a[1];g.x.beginPath();g.x.moveTo(g.pad,py);g.x.lineTo(g.w-g.pad,py);g.x.stroke();g.x.setLineDash([]);g.x.fillStyle=a[1];g.x.fillText(a[2]+" "+v.toFixed(4),g.pad+4,py-5)})}
  function multiChart(id,h,key,negative){var g=setup(id);if(h.length<2){g.x.fillStyle="#8da39b";g.x.fillText("Grafik için veri birikiyor",18,28);return}var vs=[];h.forEach(function(q){Object.keys(labels).forEach(function(k){var v=Number((q.strategies[k]||{})[key]||0);vs.push(negative?-Math.abs(v):v)})});var lo=Math.min.apply(null,vs.concat([0])),hi=Math.max.apply(null,vs.concat([0]));if(hi===lo){hi++;lo--}grid(g,lo,hi);Object.keys(labels).forEach(function(k){g.x.strokeStyle=colors[k];g.x.lineWidth=2;g.x.beginPath();h.forEach(function(q,i){var v=Number((q.strategies[k]||{})[key]||0);if(negative)v=-Math.abs(v);var px=g.pad+(g.w-g.pad*2)*i/(h.length-1),py=g.h-g.pad-(v-lo)/(hi-lo)*(g.h-g.pad*2);i?g.x.lineTo(px,py):g.x.moveTo(px,py)});g.x.stroke()})}
  function trades(q){var rows=[];Object.keys(labels).forEach(function(k){((q.strategies[k]||{}).recent_trades||[]).forEach(function(t){rows.push({k:k,t:t})})});rows.sort(function(a,b){return Number(b.t.closed_at)-Number(a.t.closed_at)});if(!rows.length){e("trades").innerHTML='<div class="empty">Henüz kapanan işlem yok. Açık pozisyonlar yukarıdaki kartlarda görünür.</div>';return}e("trades").innerHTML='<table><thead><tr><th>Strateji</th><th>Yön</th><th>Giriş</th><th>Çıkış</th><th>ROI</th><th>Neden kapandı?</th><th>Zaman</th></tr></thead><tbody>'+rows.slice(0,30).map(function(r){return'<tr><td>'+labels[r.k]+'</td><td>'+esc(String(r.t.side||"").toUpperCase())+'</td><td>'+n(r.t.entry,4)+'</td><td>'+n(r.t.exit,4)+'</td><td class="'+cls(r.t.roi_pct)+'">'+p(r.t.roi_pct)+'</td><td>'+esc(r.t.exit_reason||"—")+'</td><td>'+dt(r.t.closed_at)+'</td></tr>'}).join("")+'</tbody></table>'}
  function periods(h){if(!h.length){e("periods").innerHTML='<div class="empty">Dönem verisi bekleniyor</div>';return}function week(ms){var d=new Date(ms),shift=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-shift);return d.toISOString().slice(0,10)}function grouped(kind){var g={};h.forEach(function(q){var k=kind==="Gün"?new Date(q.market_candle).toISOString().slice(0,10):week(q.market_candle);if(!g[k])g[k]={first:q,last:q};else g[k].last=q});return Object.keys(g).sort().reverse().slice(0,kind==="Gün"?7:6).map(function(k){return{label:(kind==="Gün"?"G ":"H ")+k,pair:g[k]}})}function delta(row,s){return Number((row.pair.last.strategies[s]||{}).wallet_roi_pct||0)-Number((row.pair.first.strategies[s]||{}).wallet_roi_pct||0)}var rows=grouped("Gün").concat(grouped("Hafta"));e("periods").innerHTML='<div class="period head"><span>Dönem</span><span>Kırılım</span><span>Geri çekilme</span><span>Likidite</span></div>'+rows.map(function(r){return'<div class="period"><span>'+r.label+'</span>'+Object.keys(labels).map(function(s){var v=delta(r,s);return'<span class="'+cls(v)+'">'+p(v)+'</span>'}).join("")+'</div>'}).join("")}
  window.addEventListener("resize",function(){if(data)render()});load();setInterval(load,20000);
})();
